'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class cortes
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''lblListTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesde As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''calFechaDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calFechaDesde As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''lblHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHasta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''calFechaHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calFechaHasta As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''lblSucursal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSucursal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbSucursal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSucursal As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cortesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cortesList As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''panelDetalleCorte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDetalleCorte As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDetalleTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetalleTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFolioCorte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolioCorte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFolioCorteValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolioCorteValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSucursalCorte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSucursalCorte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSucursalCorteValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSucursalCorteValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCajeroCorte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCajeroCorte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCajeroCorteValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCajeroCorteValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechasCorte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechasCorte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechasCorteValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechasCorteValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSistema control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSistema As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEfectivoReportado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEfectivoReportado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEfectivoReportadoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEfectivoReportadoValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInicioCaja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInicioCaja As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInicioCajaValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInicioCajaValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalVentaEfectivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalVentaEfectivo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalVentaEfectivoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalVentaEfectivoValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEntradas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntradas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEntradasValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntradasValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblVales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVales As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValesValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValesValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRetiros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRetiros As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRetirosValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRetirosValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalEfectivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalEfectivo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalEfectivoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalEfectivoValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFaltanteSobrante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFaltanteSobrante As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFaltanteSobranteValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFaltanteSobranteValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblDesgloceEfectivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDesgloceEfectivo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes1000 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes1000 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes1000Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes1000Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes500 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes500Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes500Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes200 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes200Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes200Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes100 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes100Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes100Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes50 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes50Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes50Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes20 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBilletes20Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilletes20Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas20 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas20Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas20Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas10Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas10Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas5Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas5Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas2Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas2Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas1Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas1Value As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas50c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas50c As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonedas50cValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonedas50cValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblresumenVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblresumenVenta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEfectivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEfectivo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEfectivoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEfectivoValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTarjetas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarjetas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTarjetasValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarjetasValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCheques control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCheques As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblChequesValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChequesValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDepositos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepositos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDepositosValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepositosValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalVenta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalVentaValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalVentaValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalGastos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalGastos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalGastosValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalGastosValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPromedioVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPromedioVenta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPromedioVentaValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPromedioVentaValue As Global.System.Web.UI.WebControls.Label
End Class
