'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsprod1.facturehoy.com:80/CFDI/WsEmisionTimbrado")>  _
        Public ReadOnly Property LinkiumCFDI_FactureHoyNT_WsEmisionTimbradoService() As String
            Get
                Return CType(Me("LinkiumCFDI_FactureHoyNT_WsEmisionTimbradoService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsprod1.facturehoy.com:80/CFDI/WsServicios")>  _
        Public ReadOnly Property LinkiumCFDI_FactureHoyObtenerServiciosProducccion_WsServiciosService() As String
            Get
                Return CType(Me("LinkiumCFDI_FactureHoyObtenerServiciosProducccion_WsServiciosService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://pruebasclientes.facturehoy.com:8080/CFDI33/WsEmisionTimbrado33")>  _
        Public ReadOnly Property LinkiumCFDI_FactureHoyPruebasV33_WsEmisionTimbrado33() As String
            Get
                Return CType(Me("LinkiumCFDI_FactureHoyPruebasV33_WsEmisionTimbrado33"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsprod3.facturehoy.com:80/CFDI33/WsEmisionTimbrado33")>  _
        Public ReadOnly Property LinkiumCFDI_FactureHoyNT33_WsEmisionTimbrado33() As String
            Get
                Return CType(Me("LinkiumCFDI_FactureHoyNT33_WsEmisionTimbrado33"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsprod3.facturehoy.com:80/CFDI33/WsCancelacion33")>  _
        Public ReadOnly Property LinkiumCFDI_WsCancelacion33_WsCancelacion33() As String
            Get
                Return CType(Me("LinkiumCFDI_WsCancelacion33_WsCancelacion33"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://sat.sifei.com.mx:8443/SIFEI/SIFEI")>  _
        Public ReadOnly Property LinkiumCFDI_SIFEI33_SIFEIService() As String
            Get
                Return CType(Me("LinkiumCFDI_SIFEI33_SIFEIService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://devcfdi.sifei.com.mx:8080/SIFEI33/SIFEI")>  _
        Public ReadOnly Property LinkiumCFDI_SIFEIPruebasV33_SIFEIService() As String
            Get
                Return CType(Me("LinkiumCFDI_SIFEIPruebasV33_SIFEIService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://sat.sifei.com.mx:9000/CancelacionSIFEI/Cancelacion")>  _
        Public ReadOnly Property LinkiumCFDI_CancelacionSIFEI_Cancelacion() As String
            Get
                Return CType(Me("LinkiumCFDI_CancelacionSIFEI_Cancelacion"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LinkiumCFDI.My.MySettings
            Get
                Return Global.LinkiumCFDI.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
